---
# SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
# SPDX-License-Identifier: Apache-2.0

image:
  tag: 0.3.0

gpu:
  profile: a100
  count: 8

nodeSelector:
  scheduler.slinky.slurm.net/slurm-bridge: worker

tolerations:
  - key: slinky.slurm.net/managed-node
    operator: Equal
    value: slurm-bridge-scheduler
    effect: NoExecute
