---
apiVersion: scheduling.k8s.io/v1alpha2
kind: Workload
metadata:
  name: training-workload
  namespace: slurm-bridge
  annotations:
    slurmjob.slinky.slurm.net/job-name: training-job
    slurmjob.slinky.slurm.net/timelimit: '5'
spec:
  controllerRef:
    apiGroup: batch
    kind: Job
    name: training-job
  podGroupTemplates:
    - name: workers
      schedulingPolicy:
        gang:
          minCount: 2
---
apiVersion: scheduling.k8s.io/v1alpha2
kind: PodGroup
metadata:
  name: training-job-workers
  namespace: slurm-bridge
spec:
  podGroupTemplateRef:
    workload:
      workloadName: training-workload
      podGroupTemplateName: workers
  schedulingPolicy:
    gang:
      minCount: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  name: training-job
  namespace: slurm-bridge
spec:
  parallelism: 2
  completions: 2
  completionMode: NonIndexed
  template:
    spec:
      schedulerName: slurm-bridge-scheduler
      restartPolicy: Never
      schedulingGroup:
        podGroupName: training-job-workers
      containers:
        - name: worker
          image: busybox:stable
          command: [sh, -c, sleep 20]
          resources:
            requests:
              cpu: '1'
              memory: 100Mi
            limits:
              cpu: '1'
              memory: 100Mi
