---
version: '2'
run:
  tests: true
linters:
  enable:
    - asasalint
    - errcheck
    - errorlint
    - gocritic
    - gosec
    - ineffassign
    - misspell
    - nilnil
    - nilerr
    - unused
    - wastedassign
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    misspell:
      locale: US
formatters:
  enable:
    - gci
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/SlinkyProject)
        - localmodule
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
