{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slurm-bridge.controllers.name" . }}
  namespace: {{ include "slurm-bridge.namespace" . }}
  labels:
    {{- include "slurm-bridge.controllers.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllers.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "slurm-bridge.controllers.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "slurm-bridge.controllers.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.controllers.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "slurm-bridge.controllers.name" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 10}}
      {{- end }}
      containers:
        - name: {{ include "slurm-bridge.controllers.name" . }}
          image: {{ include "slurm-bridge.controllers.imageRef" . }}
          imagePullPolicy: {{ .Values.controllers.image.pullPolicy }}
          env:
            - name: SLURM_JWT_FILE
              value: /var/run/secrets/slurm/auth-token
          args:
            - -zap-log-level
            - {{ .Values.controllers.verbosity | default "info" | quote }}
            - --leader-elect={{ .Values.controllers.leaderElect }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
          {{- with .Values.controllers.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: slurm-bridge-config
              mountPath: /etc/slurm-bridge/
              readOnly: true
            - name: slurm-jwt
              mountPath: /var/run/secrets/slurm
              readOnly: true
      {{- with .Values.controllers.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controllers.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controllers.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: slurm-bridge-config
          configMap:
            name: slurm-bridge-config
        - name: slurm-jwt
          secret:
            secretName: {{ .Values.sharedConfig.slurmJwtSecret }}
            items:
              - key: auth-token
                path: auth-token
