---
# SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
# SPDX-License-Identifier: Apache-2.0

gpuResourcesEnabledOverride: true

resources:
  gpus:
    enabled: true
  computeDomains:
    enabled: false

kubeletPlugin:
  nodeSelector:
    scheduler.slinky.slurm.net/slurm-bridge: worker
  tolerations:
    - key: slinky.slurm.net/managed-node
      operator: Equal
      value: slurm-bridge-scheduler
      effect: NoExecute
