rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - resource.k8s.io
    resources:
      - deviceclasses
    verbs:
      - get
      - list
      - watch
