rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/finalizers
    verbs:
      - patch
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
  - apiGroups:
      - resource.k8s.io
    resources:
      - resourceclaims
    verbs:
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - resource.k8s.io
    resources:
      - resourceslices
    verbs:
      - get
      - list
      - watch
